# Generated by Django 5.2.4 on 2025-07-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Quotes', 'Quotes'), ('CDC Assessment', 'CDC Assessment'), ('SC Assessment', 'SC Assessment'), ('Finalized', 'Finalized')], max_length=100),
        ),
    ]
